# Generated by Django 5.2.1 on 2025-05-23 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomapp', '0003_passwordresetotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True, null=True)),
                ('room_type', models.CharField(blank=True, choices=[('single', 'Single'), ('double', 'Double'), ('suite', 'Suite')], max_length=10, null=True)),
                ('room_number', models.CharField(max_length=20, unique=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('ac', 'AC'), ('non_ac', 'Non-AC')], max_length=10, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('maintenance', 'Maintenance')], default='available', max_length=15)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='cover_images/')),
                ('facilities', models.ManyToManyField(blank=True, to='roomapp.facility')),
            ],
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='roomapp.room')),
            ],
        ),
    ]
